version: "3"
services:
    nodeserver:
        build:
            context: ./node
        ports:
            - "5000:5000"
    # nginx:
    #     build:
    #         context: ./nginx
    #     ports:
    #         - "8080:80"
