version: "3"
services:
    redis-server:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    nodeserver:
        restart: on-failure
        build:
            network: host
            context: ./nodejs
        depends_on:
            - redis-server
        # ports:
        #     - "5000:5000"
    goserver:
        restart: on-failure
        build:
            network: host
            context: ./go
        depends_on:
            - redis-server
        # ports:
        #     - "8080:8080"
    nginx:
        restart: on-failure
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports:
            - "8000:80"
        # depends_on:
        #     - goserver
        #     - nodeserver