version: "3"
services:
    redis-server:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    nodeserver:
        restart: on-failure
        build:
            network: host
            context: ./node
        ports:
            - "5000:5000"
    goserver:
        restart: on-failure
        build:
            network: host
            context: ./GO
        ports:
            - "8080:8080"
    nginx:
        restart: on-failure
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports:
            - "80:80"