version: "3"
services:
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    nodeserver:
        build:
            network: host
            context: ./node
        ports:
            - "5000:5000"
        depends_on:
            - "redis"
    goserver:
        build:
            network: host
            context: ./GO
        ports:
            - "8080:8080"
        depends_on:
            - "redis"
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - "goserver"
            - "nodeserver"